---
extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:react/recommended
  - plugin:import/react

plugins:
  - jest

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx

env:
  es2021: true
  node: true
  jest: true
  browser: true

rules:
  react/prefer-stateless-function: 1
  react/state-in-constructor: 0
  react/react-in-jsx-scope: 0
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  import/no-import-module-exports: 0
  react/display-name: 0
